"""Complete the product schema: users + RBAC, the CRM follow-up list, chat
history with citations, generated FCR reports, and the access audit trail.

Autogenerated then hand-reviewed: the ix_kb_chunks_embedding_hnsw drop that
autogenerate proposed was removed (that index is created dialect-guarded in
0001 and intentionally absent from models.py), and now() defaults were
rewritten as CURRENT_TIMESTAMP so the migration also runs on SQLite (tests).

Revision ID: 0003_full_product_schema
Revises: a64413ab4fa6
Create Date: 2026-07-19
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0003_full_product_schema"
# Chained after Person B's Sprint 4 migrations (customers, agents) when the two
# branches merged, so the DAG has a single head. This adds only the tables those
# two don't touch; customers gains its extra columns in 0005.
down_revision: Union[str, None] = "a64413ab4fa6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_NOW = sa.text("CURRENT_TIMESTAMP")


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), server_default="agent", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.CheckConstraint("role IN ('agent', 'quality_manager', 'admin')", name="ck_users_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("username", name="uq_users_username"),
    )

    op.create_table(
        "follow_up_tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crm_ticket_id", sa.String(length=64), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=True),
        sa.Column("customer_phone", sa.String(length=20), nullable=False),
        sa.Column("procedure", sa.String(length=255), nullable=True),
        sa.Column("issue_summary", sa.Text(), nullable=True),
        sa.Column("inbound_call_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "follow_up_status", sa.String(length=16), server_default="pending", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.CheckConstraint(
            "follow_up_status IN ('pending', 'queued', 'in_progress', 'resolved', "
            "'escalated', 'cancelled')",
            name="ck_follow_up_tickets_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crm_ticket_id", name="uq_follow_up_tickets_crm_ticket_id"),
    )
    op.create_index(
        "ix_follow_up_tickets_customer_phone", "follow_up_tickets", ["customer_phone"]
    )
    op.create_index(
        "ix_follow_up_tickets_status_created",
        "follow_up_tickets",
        ["follow_up_status", "created_at"],
    )

    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_chat_sessions_user_id", "chat_sessions", ["user_id"])

    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sources", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.CheckConstraint("role IN ('user', 'assistant')", name="ck_chat_messages_role"),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0", name="ck_chat_messages_latency_nonnegative"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_messages_session_created", "chat_messages", ["session_id", "created_at"]
    )

    op.create_table(
        "fcr_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_calls", sa.Integer(), server_default="0", nullable=False),
        sa.Column("resolved_first_attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fcr_rate", sa.Float(), nullable=True),
        sa.Column("completion_rate", sa.Float(), nullable=True),
        sa.Column("average_handle_time_seconds", sa.Float(), nullable=True),
        sa.Column("report_markdown", sa.Text(), nullable=True),
        sa.Column("generated_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.CheckConstraint(
            "completion_rate IS NULL OR (completion_rate >= 0 AND completion_rate <= 1)",
            name="ck_fcr_reports_completion_rate_range",
        ),
        sa.CheckConstraint(
            "fcr_rate IS NULL OR (fcr_rate >= 0 AND fcr_rate <= 1)",
            name="ck_fcr_reports_fcr_rate_range",
        ),
        sa.CheckConstraint("period_end >= period_start", name="ck_fcr_reports_period"),
        sa.ForeignKeyConstraint(["generated_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("period_start", "period_end", name="uq_fcr_reports_period"),
    )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_logs_action_created", "audit_logs", ["action", "created_at"])
    op.create_index("ix_audit_logs_user_created", "audit_logs", ["user_id", "created_at"])


def downgrade() -> None:
    op.drop_index("ix_audit_logs_user_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("fcr_reports")
    op.drop_index("ix_chat_messages_session_created", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("ix_chat_sessions_user_id", table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index("ix_follow_up_tickets_status_created", table_name="follow_up_tickets")
    op.drop_index("ix_follow_up_tickets_customer_phone", table_name="follow_up_tickets")
    op.drop_table("follow_up_tickets")
    op.drop_table("users")
